# Example/Documentation for the IG YML file
# https://fshschool.org/docs/sushi/configuration/#exhaustive-example

# Package name
# https://confluence.hl7.org/display/FHIR/NPM+Package+Specification#NPMPackageSpecification-Packagename
id: ch.fhir.ig.swissnoso
canonical: http://fhir.ch/ig/swissnoso
name: Swissnoso_IG
title: Swissnoso Implementation Guide (R4)
description: Implementation guide to specify the exchange format for data transmission to Swissnoso in the context of monitoring and prevention of healthcare-associated infections.
status: active
license: CC-BY-SA-4.0
copyright: CC-BY-SA-4.0
jurisdiction: urn:iso:std:iso:3166#CHE
date: 2022-06-14
version: 1.0.0
fhirVersion: 4.0.1
copyrightYear: 2022+
# https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters -> Parameter: releaselabel
releaseLabel: STU 1 
publisher:
  name: Swissnoso
contact:
  name: Swissnoso
  telecom:
    system: url
    value: https://www.swissnoso.ch/

dependencies:
  ch.fhir.ig.ch-core: 2.0.0

pages:
  index.md:
    title: Home
  usecases-de.md:
    title: Anwendungsfälle
  usecases-fr.md:
    title: Cas d'application
  usecases-it.md:
    title: Casi concreti     
  message.md:
    title: Message
  profiles.md:
    title: Profiles
  extensions.md:
    title: Extensions
  terminology.md:
    title: Terminology
  changelog.md:
    title: Change Log    

# Parameters
# https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters

